version: '3.7'
services:

  myproj_redis:
    image: redis:4.0.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  myproj_api:
    build:
        context: .
        dockerfile: ./compose/local/fastapi/Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 5057
    ports:
      - "5057:5057"
    depends_on:
      - myproj_redis
    links:
      - myproj_redis

  myproj_worker:
    build:
        context: .
        dockerfile: ./compose/local/fastapi/Dockerfile
    command: rq worker --with-scheduler --url redis://myproj_redis:6379
    depends_on:
      - myproj_redis
    links:
      - myproj_redis