version: '3.7'
services:

  myproj_redis:
    image: redis:4.0.6
    environment: 
      TZ: America/Bogota
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  myproj_api:
    build:
        context: .
        dockerfile: ./compose/local/fastapi/Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8083 --reload
    volumes:
      - type: bind
        source: ./
        target: /home/scheduler
    ports:
      - "8083:8083"
    depends_on:
      - myproj_redis
    links:
      - myproj_redis
    networks: 
      - scheduler_redis_python_default
      - intermediate_network

  myproj_worker:
    build:
        context: .
        dockerfile: ./compose/local/fastapi/Dockerfile
    command: rq worker --with-scheduler --url redis://myproj_redis:6379
    depends_on:
      - myproj_redis
    links:
      - myproj_redis

networks: 
  intermediate_network:
    driver: bridge
    name: intermediate_network
  scheduler_redis_python_default:
    external: true
    name: scheduler_redis_python_default